import { TranslocoTestingModule, TranslocoTestingOptions } from '@jsverse/transloco';

/**
 * Synchronous in-memory translations for specs — keeps component tests from depending on the
 * runtime HTTP loader (`public/i18n/*.json`) that only exists once the app is actually served.
 */
export function getTranslocoTestingModule(options: TranslocoTestingOptions = {}) {
  return TranslocoTestingModule.forRoot({
    langs: {
      de: {
        app: { title: 'Team-Terminkalender' },
        login: {
          heading: 'Anmelden',
          emailLabel: 'E-Mail',
          passwordLabel: 'Passwort',
          submit: 'Anmelden',
          genericError: 'Anmeldung fehlgeschlagen. Bitte überprüfe deine Zugangsdaten.',
        },
        nav: { logout: 'Abmelden', settings: 'Einstellungen', syncOverview: 'Sync-Übersicht' },
        calendar: {
          viewMonth: 'Monat',
          viewWeek: 'Woche',
          viewDay: 'Tag',
          viewSwitcherLabel: 'Ansicht',
          previous: 'Zurück',
          next: 'Weiter',
          today: 'Heute',
          empty: 'Du hast noch keine Termine.',
          emptyNoConnectionPrefix: 'Noch keine Termine — verbinde deinen Kalender in den ',
          emptyNoConnectionLink: 'Einstellungen',
          emptyNoConnectionSuffix: ', wann immer du bereit bist.',
          createButton: '+ Neuer Termin',
          createHeading: 'Neuer Termin',
          createFieldTitle: 'Titel',
          createFieldDate: 'Datum',
          createFieldStart: 'Startzeit',
          createFieldDuration: 'Dauer',
          createFieldEnd: 'Ende',
          createFieldAttendees: 'Teilnehmer (optional)',
          createTitleRequired: 'Bitte gib einen Titel ein.',
          createInvalidTimeRange: 'Die Endzeit muss nach der Startzeit liegen.',
          createAttendeeNotFound: 'Mindestens ein Teilnehmer ist nicht mehr verfügbar. Bitte Auswahl prüfen.',
          createCancel: 'Abbrechen',
          createSave: 'Speichern',
          addAttendee: '+ Teilnehmer hinzufügen',
          statusInterruptible: 'Unterbrechbar',
          statusDnd: 'Bitte nicht stören',
          detailClose: 'Schließen',
          detailFieldDate: 'Datum',
          detailFieldTime: 'Zeit',
          detailFieldStatus: 'Status',
          detailFieldAttendees: 'Teilnehmer',
          detailNoAttendees: 'Keine Teilnehmer',
          detailLoadError: 'Termin konnte nicht geladen werden.',
          detailPrivateTitle: 'Privat / beschäftigt',
          detailPrivacyNote: 'Details sind privat — nur der Status ist sichtbar.',
          colleagueSlotLabel: 'Termin, Status: {{status}}',
          ownColumnLabel: 'Ich',
          personSelectorAddLabel: 'Teammitglied hinzufügen',
          personSelectorSearchPlaceholder: 'Teammitglied suchen …',
          personSelectorRemoveLabel: '{{email}} entfernen',
          personSelectorEmptyHint: 'Wähle Teammitglieder, um ihre Verfügbarkeit zu sehen.',
          monthAggregateMarker: '{{count}} Bitte nicht stören',
        },
        languageSwitcher: { groupLabel: 'Sprache', de: 'DE', en: 'EN' },
        settings: {
          connections: {
            crumbHome: 'Kalender',
            crumbConnections: 'Kalenderverbindungen',
            heading: 'Kalenderverbindungen',
            sub: 'Verbinde deinen Outlook- oder Google-Kalender, damit deine Termine automatisch importiert werden. Die Synchronisierung läuft alle paar Minuten in eine Richtung — es wird nichts in dein Konto zurückgeschrieben.',
            statusConnected: 'Verbunden',
            statusNotConnected: 'Nicht verbunden',
            statusError: 'Verbindungsfehler',
            connect: 'Verbinden',
            retry: 'Erneut versuchen',
            disconnect: 'Verbindung trennen',
            disconnectConfirm: '{{provider}}-Verbindung wirklich trennen? Alle daraus importierten Termine werden entfernt.',
            connectedNotice: '{{provider}}-Kalender erfolgreich verbunden.',
            lastSync: 'Zuletzt synchronisiert vor {{minutes}} Min.',
            neverSynced: 'Kein erfolgreicher Sync bisher',
            error: {
              consent_denied: 'Verbindung abgelehnt — der Zustimmung zum Kalenderzugriff wurde nicht erteilt.',
              tenant_blocked: 'Verbindung von deinem Unternehmen blockiert — bitte den IT-Admin kontaktieren.',
              code_missing: 'Verbindung fehlgeschlagen — bitte erneut versuchen.',
              no_refresh_token_returned: 'Verbindung fehlgeschlagen — bitte erneut versuchen.',
              invalid_state: 'Verbindung fehlgeschlagen — bitte erneut versuchen.',
              oauth_error: 'Verbindung fehlgeschlagen — bitte erneut versuchen.',
              code_exchange_failed: 'Verbindung fehlgeschlagen — bitte erneut versuchen.',
              token_refresh_failed: 'Synchronisierung fehlgeschlagen — bitte Verbindung erneut herstellen.',
              provider_error: 'Synchronisierung derzeit nicht möglich — wird automatisch erneut versucht.',
              unknown_error: 'Synchronisierung fehlgeschlagen — wird automatisch erneut versucht.',
            },
          },
        },
        admin: {
          syncOverview: {
            crumbHome: 'Kalender',
            crumbOverview: 'Sync-Übersicht',
            heading: 'Sync-Übersicht',
            columnPerson: 'Person',
            columnProvider: 'Provider',
            columnStatus: 'Status',
            columnLastSync: 'Letzter Sync',
            forbidden: 'Kein Zugriff — diese Seite ist nur für Admins.',
          },
        },
      },
      en: {
        app: { title: 'Team Calendar' },
        login: {
          heading: 'Sign in',
          emailLabel: 'Email',
          passwordLabel: 'Password',
          submit: 'Sign in',
          genericError: 'Sign-in failed. Please check your credentials.',
        },
        nav: { logout: 'Sign out', settings: 'Settings', syncOverview: 'Sync overview' },
        calendar: {
          viewMonth: 'Month',
          viewWeek: 'Week',
          viewDay: 'Day',
          viewSwitcherLabel: 'View',
          previous: 'Previous',
          next: 'Next',
          today: 'Today',
          empty: "You don't have any appointments yet.",
          emptyNoConnectionPrefix: 'No appointments yet — connect your calendar in ',
          emptyNoConnectionLink: 'Settings',
          emptyNoConnectionSuffix: " whenever you're ready.",
          createButton: '+ New appointment',
          createHeading: 'New appointment',
          createFieldTitle: 'Title',
          createFieldDate: 'Date',
          createFieldStart: 'Start time',
          createFieldDuration: 'Duration',
          createFieldEnd: 'End',
          createFieldAttendees: 'Attendees (optional)',
          createTitleRequired: 'Please enter a title.',
          createInvalidTimeRange: 'The end time must be after the start time.',
          createAttendeeNotFound: 'At least one attendee is no longer available. Please check your selection.',
          createCancel: 'Cancel',
          createSave: 'Save',
          addAttendee: '+ Add attendee',
          statusInterruptible: 'Interruptible',
          statusDnd: 'Do not disturb',
          detailClose: 'Close',
          detailFieldDate: 'Date',
          detailFieldTime: 'Time',
          detailFieldStatus: 'Status',
          detailFieldAttendees: 'Attendees',
          detailNoAttendees: 'No attendees',
          detailLoadError: 'Could not load this appointment.',
          detailPrivateTitle: 'Private / busy',
          detailPrivacyNote: 'Details are private — only the status is visible.',
          colleagueSlotLabel: 'Appointment, status: {{status}}',
          ownColumnLabel: 'Me',
          personSelectorAddLabel: 'Add teammate',
          personSelectorSearchPlaceholder: 'Search teammate …',
          personSelectorRemoveLabel: 'Remove {{email}}',
          personSelectorEmptyHint: 'Choose teammates to see their availability.',
          monthAggregateMarker: '{{count}} do not disturb',
        },
        languageSwitcher: { groupLabel: 'Language', de: 'DE', en: 'EN' },
        settings: {
          connections: {
            crumbHome: 'Calendar',
            crumbConnections: 'Calendar connections',
            heading: 'Calendar connections',
            sub: "Connect your Outlook or Google calendar so your appointments are imported automatically. Sync runs one-way every few minutes — nothing is ever written back to your account.",
            statusConnected: 'Connected',
            statusNotConnected: 'Not connected',
            statusError: 'Connection error',
            connect: 'Connect',
            retry: 'Retry',
            disconnect: 'Disconnect',
            disconnectConfirm: 'Disconnect {{provider}}? All appointments imported from it will be removed.',
            connectedNotice: '{{provider}} Calendar connected successfully.',
            lastSync: 'Last synced {{minutes}} min ago.',
            neverSynced: 'No successful sync yet',
            error: {
              consent_denied: 'Connection declined — consent to calendar access was not granted.',
              tenant_blocked: 'Connection blocked by your organization — please contact your IT admin.',
              code_missing: 'Connection failed — please try again.',
              no_refresh_token_returned: 'Connection failed — please try again.',
              invalid_state: 'Connection failed — please try again.',
              oauth_error: 'Connection failed — please try again.',
              code_exchange_failed: 'Connection failed — please try again.',
              token_refresh_failed: 'Sync failed — please reconnect your account.',
              provider_error: "Sync isn't working right now — it will retry automatically.",
              unknown_error: 'Sync failed — it will retry automatically.',
            },
          },
        },
        admin: {
          syncOverview: {
            crumbHome: 'Calendar',
            crumbOverview: 'Sync overview',
            heading: 'Sync overview',
            columnPerson: 'Person',
            columnProvider: 'Provider',
            columnStatus: 'Status',
            columnLastSync: 'Last sync',
            forbidden: 'Access denied — this page is for admins only.',
          },
        },
      },
    },
    translocoConfig: {
      availableLangs: ['de', 'en'],
      defaultLang: 'de',
      fallbackLang: 'de',
      reRenderOnLangChange: true,
    },
    preloadLangs: true,
    ...options,
  });
}
